// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YLMessageModel.proto

package com.hoggen.sublimation.proto;

public final class MessageModel {
  private MessageModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface YLUserModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YLUserModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    java.lang.String getAvatar();
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();
  }
  /**
   * <pre>
   * 用户单聊信息模型
   * </pre>
   *
   * Protobuf type {@code YLUserModel}
   */
  public  static final class YLUserModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:YLUserModel)
      YLUserModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use YLUserModel.newBuilder() to construct.
    private YLUserModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private YLUserModel() {
      userId_ = "";
      name_ = "";
      avatar_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private YLUserModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoggen.sublimation.proto.MessageModel.internal_static_YLUserModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoggen.sublimation.proto.MessageModel.internal_static_YLUserModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoggen.sublimation.proto.MessageModel.YLUserModel.class, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    private volatile java.lang.Object avatar_;
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoggen.sublimation.proto.MessageModel.YLUserModel)) {
        return super.equals(obj);
      }
      com.hoggen.sublimation.proto.MessageModel.YLUserModel other = (com.hoggen.sublimation.proto.MessageModel.YLUserModel) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getName()
          .equals(other.getName());
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoggen.sublimation.proto.MessageModel.YLUserModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 用户单聊信息模型
     * </pre>
     *
     * Protobuf type {@code YLUserModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:YLUserModel)
        com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoggen.sublimation.proto.MessageModel.internal_static_YLUserModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoggen.sublimation.proto.MessageModel.internal_static_YLUserModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoggen.sublimation.proto.MessageModel.YLUserModel.class, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder.class);
      }

      // Construct using com.hoggen.sublimation.proto.MessageModel.YLUserModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        name_ = "";

        avatar_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoggen.sublimation.proto.MessageModel.internal_static_YLUserModel_descriptor;
      }

      public com.hoggen.sublimation.proto.MessageModel.YLUserModel getDefaultInstanceForType() {
        return com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance();
      }

      public com.hoggen.sublimation.proto.MessageModel.YLUserModel build() {
        com.hoggen.sublimation.proto.MessageModel.YLUserModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoggen.sublimation.proto.MessageModel.YLUserModel buildPartial() {
        com.hoggen.sublimation.proto.MessageModel.YLUserModel result = new com.hoggen.sublimation.proto.MessageModel.YLUserModel(this);
        result.userId_ = userId_;
        result.name_ = name_;
        result.avatar_ = avatar_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoggen.sublimation.proto.MessageModel.YLUserModel) {
          return mergeFrom((com.hoggen.sublimation.proto.MessageModel.YLUserModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoggen.sublimation.proto.MessageModel.YLUserModel other) {
        if (other == com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoggen.sublimation.proto.MessageModel.YLUserModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoggen.sublimation.proto.MessageModel.YLUserModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像
       * </pre>
       *
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:YLUserModel)
    }

    // @@protoc_insertion_point(class_scope:YLUserModel)
    private static final com.hoggen.sublimation.proto.MessageModel.YLUserModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoggen.sublimation.proto.MessageModel.YLUserModel();
    }

    public static com.hoggen.sublimation.proto.MessageModel.YLUserModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<YLUserModel>
        PARSER = new com.google.protobuf.AbstractParser<YLUserModel>() {
      public YLUserModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new YLUserModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<YLUserModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<YLUserModel> getParserForType() {
      return PARSER;
    }

    public com.hoggen.sublimation.proto.MessageModel.YLUserModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface YLMessageModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YLMessageModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>.YLUserModel fromUser = 1;</code>
     */
    boolean hasFromUser();
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>.YLUserModel fromUser = 1;</code>
     */
    com.hoggen.sublimation.proto.MessageModel.YLUserModel getFromUser();
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>.YLUserModel fromUser = 1;</code>
     */
    com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder getFromUserOrBuilder();

    /**
     * <pre>
     *送达人
     * </pre>
     *
     * <code>.YLUserModel toUser = 2;</code>
     */
    boolean hasToUser();
    /**
     * <pre>
     *送达人
     * </pre>
     *
     * <code>.YLUserModel toUser = 2;</code>
     */
    com.hoggen.sublimation.proto.MessageModel.YLUserModel getToUser();
    /**
     * <pre>
     *送达人
     * </pre>
     *
     * <code>.YLUserModel toUser = 2;</code>
     */
    com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder getToUserOrBuilder();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 messageType = 3;</code>
     */
    int getMessageType();

    /**
     * <pre>
     *消息字符
     * </pre>
     *
     * <code>string textString = 4;</code>
     */
    java.lang.String getTextString();
    /**
     * <pre>
     *消息字符
     * </pre>
     *
     * <code>string textString = 4;</code>
     */
    com.google.protobuf.ByteString
        getTextStringBytes();

    /**
     * <pre>
     *消息资源地址（如图片、视频、文件）
     * </pre>
     *
     * <code>string messageSource = 5;</code>
     */
    java.lang.String getMessageSource();
    /**
     * <pre>
     *消息资源地址（如图片、视频、文件）
     * </pre>
     *
     * <code>string messageSource = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageSourceBytes();

    /**
     * <pre>
     *录音时长
     * </pre>
     *
     * <code>uint32 voiceLength = 6;</code>
     */
    int getVoiceLength();

    /**
     * <pre>
     *录音数据
     * </pre>
     *
     * <code>bytes voiceData = 7;</code>
     */
    com.google.protobuf.ByteString getVoiceData();

    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 8;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 8;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string messageId = 9;</code>
     */
    java.lang.String getMessageId();
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string messageId = 9;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();
  }
  /**
   * <pre>
   * 用户单聊信息模型
   * </pre>
   *
   * Protobuf type {@code YLMessageModel}
   */
  public  static final class YLMessageModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:YLMessageModel)
      YLMessageModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use YLMessageModel.newBuilder() to construct.
    private YLMessageModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private YLMessageModel() {
      messageType_ = 0;
      textString_ = "";
      messageSource_ = "";
      voiceLength_ = 0;
      voiceData_ = com.google.protobuf.ByteString.EMPTY;
      token_ = "";
      messageId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private YLMessageModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder subBuilder = null;
              if (fromUser_ != null) {
                subBuilder = fromUser_.toBuilder();
              }
              fromUser_ = input.readMessage(com.hoggen.sublimation.proto.MessageModel.YLUserModel.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fromUser_);
                fromUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder subBuilder = null;
              if (toUser_ != null) {
                subBuilder = toUser_.toBuilder();
              }
              toUser_ = input.readMessage(com.hoggen.sublimation.proto.MessageModel.YLUserModel.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(toUser_);
                toUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              messageType_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              textString_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              messageSource_ = s;
              break;
            }
            case 48: {

              voiceLength_ = input.readUInt32();
              break;
            }
            case 58: {

              voiceData_ = input.readBytes();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hoggen.sublimation.proto.MessageModel.internal_static_YLMessageModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hoggen.sublimation.proto.MessageModel.internal_static_YLMessageModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hoggen.sublimation.proto.MessageModel.YLMessageModel.class, com.hoggen.sublimation.proto.MessageModel.YLMessageModel.Builder.class);
    }

    public static final int FROMUSER_FIELD_NUMBER = 1;
    private com.hoggen.sublimation.proto.MessageModel.YLUserModel fromUser_;
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>.YLUserModel fromUser = 1;</code>
     */
    public boolean hasFromUser() {
      return fromUser_ != null;
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>.YLUserModel fromUser = 1;</code>
     */
    public com.hoggen.sublimation.proto.MessageModel.YLUserModel getFromUser() {
      return fromUser_ == null ? com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance() : fromUser_;
    }
    /**
     * <pre>
     *发送人
     * </pre>
     *
     * <code>.YLUserModel fromUser = 1;</code>
     */
    public com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder getFromUserOrBuilder() {
      return getFromUser();
    }

    public static final int TOUSER_FIELD_NUMBER = 2;
    private com.hoggen.sublimation.proto.MessageModel.YLUserModel toUser_;
    /**
     * <pre>
     *送达人
     * </pre>
     *
     * <code>.YLUserModel toUser = 2;</code>
     */
    public boolean hasToUser() {
      return toUser_ != null;
    }
    /**
     * <pre>
     *送达人
     * </pre>
     *
     * <code>.YLUserModel toUser = 2;</code>
     */
    public com.hoggen.sublimation.proto.MessageModel.YLUserModel getToUser() {
      return toUser_ == null ? com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance() : toUser_;
    }
    /**
     * <pre>
     *送达人
     * </pre>
     *
     * <code>.YLUserModel toUser = 2;</code>
     */
    public com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder getToUserOrBuilder() {
      return getToUser();
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 3;
    private int messageType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>uint32 messageType = 3;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    public static final int TEXTSTRING_FIELD_NUMBER = 4;
    private volatile java.lang.Object textString_;
    /**
     * <pre>
     *消息字符
     * </pre>
     *
     * <code>string textString = 4;</code>
     */
    public java.lang.String getTextString() {
      java.lang.Object ref = textString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        textString_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息字符
     * </pre>
     *
     * <code>string textString = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTextStringBytes() {
      java.lang.Object ref = textString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGESOURCE_FIELD_NUMBER = 5;
    private volatile java.lang.Object messageSource_;
    /**
     * <pre>
     *消息资源地址（如图片、视频、文件）
     * </pre>
     *
     * <code>string messageSource = 5;</code>
     */
    public java.lang.String getMessageSource() {
      java.lang.Object ref = messageSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageSource_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息资源地址（如图片、视频、文件）
     * </pre>
     *
     * <code>string messageSource = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageSourceBytes() {
      java.lang.Object ref = messageSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VOICELENGTH_FIELD_NUMBER = 6;
    private int voiceLength_;
    /**
     * <pre>
     *录音时长
     * </pre>
     *
     * <code>uint32 voiceLength = 6;</code>
     */
    public int getVoiceLength() {
      return voiceLength_;
    }

    public static final int VOICEDATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString voiceData_;
    /**
     * <pre>
     *录音数据
     * </pre>
     *
     * <code>bytes voiceData = 7;</code>
     */
    public com.google.protobuf.ByteString getVoiceData() {
      return voiceData_;
    }

    public static final int TOKEN_FIELD_NUMBER = 8;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 8;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string token = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEID_FIELD_NUMBER = 9;
    private volatile java.lang.Object messageId_;
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string messageId = 9;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *token
     * </pre>
     *
     * <code>string messageId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromUser_ != null) {
        output.writeMessage(1, getFromUser());
      }
      if (toUser_ != null) {
        output.writeMessage(2, getToUser());
      }
      if (messageType_ != 0) {
        output.writeUInt32(3, messageType_);
      }
      if (!getTextStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, textString_);
      }
      if (!getMessageSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, messageSource_);
      }
      if (voiceLength_ != 0) {
        output.writeUInt32(6, voiceLength_);
      }
      if (!voiceData_.isEmpty()) {
        output.writeBytes(7, voiceData_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, token_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, messageId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFromUser());
      }
      if (toUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getToUser());
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, messageType_);
      }
      if (!getTextStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, textString_);
      }
      if (!getMessageSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, messageSource_);
      }
      if (voiceLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, voiceLength_);
      }
      if (!voiceData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, voiceData_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, token_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, messageId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hoggen.sublimation.proto.MessageModel.YLMessageModel)) {
        return super.equals(obj);
      }
      com.hoggen.sublimation.proto.MessageModel.YLMessageModel other = (com.hoggen.sublimation.proto.MessageModel.YLMessageModel) obj;

      boolean result = true;
      result = result && (hasFromUser() == other.hasFromUser());
      if (hasFromUser()) {
        result = result && getFromUser()
            .equals(other.getFromUser());
      }
      result = result && (hasToUser() == other.hasToUser());
      if (hasToUser()) {
        result = result && getToUser()
            .equals(other.getToUser());
      }
      result = result && (getMessageType()
          == other.getMessageType());
      result = result && getTextString()
          .equals(other.getTextString());
      result = result && getMessageSource()
          .equals(other.getMessageSource());
      result = result && (getVoiceLength()
          == other.getVoiceLength());
      result = result && getVoiceData()
          .equals(other.getVoiceData());
      result = result && getToken()
          .equals(other.getToken());
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFromUser()) {
        hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
        hash = (53 * hash) + getFromUser().hashCode();
      }
      if (hasToUser()) {
        hash = (37 * hash) + TOUSER_FIELD_NUMBER;
        hash = (53 * hash) + getToUser().hashCode();
      }
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + TEXTSTRING_FIELD_NUMBER;
      hash = (53 * hash) + getTextString().hashCode();
      hash = (37 * hash) + MESSAGESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageSource().hashCode();
      hash = (37 * hash) + VOICELENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getVoiceLength();
      hash = (37 * hash) + VOICEDATA_FIELD_NUMBER;
      hash = (53 * hash) + getVoiceData().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hoggen.sublimation.proto.MessageModel.YLMessageModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 用户单聊信息模型
     * </pre>
     *
     * Protobuf type {@code YLMessageModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:YLMessageModel)
        com.hoggen.sublimation.proto.MessageModel.YLMessageModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hoggen.sublimation.proto.MessageModel.internal_static_YLMessageModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hoggen.sublimation.proto.MessageModel.internal_static_YLMessageModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hoggen.sublimation.proto.MessageModel.YLMessageModel.class, com.hoggen.sublimation.proto.MessageModel.YLMessageModel.Builder.class);
      }

      // Construct using com.hoggen.sublimation.proto.MessageModel.YLMessageModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }
        if (toUserBuilder_ == null) {
          toUser_ = null;
        } else {
          toUser_ = null;
          toUserBuilder_ = null;
        }
        messageType_ = 0;

        textString_ = "";

        messageSource_ = "";

        voiceLength_ = 0;

        voiceData_ = com.google.protobuf.ByteString.EMPTY;

        token_ = "";

        messageId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hoggen.sublimation.proto.MessageModel.internal_static_YLMessageModel_descriptor;
      }

      public com.hoggen.sublimation.proto.MessageModel.YLMessageModel getDefaultInstanceForType() {
        return com.hoggen.sublimation.proto.MessageModel.YLMessageModel.getDefaultInstance();
      }

      public com.hoggen.sublimation.proto.MessageModel.YLMessageModel build() {
        com.hoggen.sublimation.proto.MessageModel.YLMessageModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hoggen.sublimation.proto.MessageModel.YLMessageModel buildPartial() {
        com.hoggen.sublimation.proto.MessageModel.YLMessageModel result = new com.hoggen.sublimation.proto.MessageModel.YLMessageModel(this);
        if (fromUserBuilder_ == null) {
          result.fromUser_ = fromUser_;
        } else {
          result.fromUser_ = fromUserBuilder_.build();
        }
        if (toUserBuilder_ == null) {
          result.toUser_ = toUser_;
        } else {
          result.toUser_ = toUserBuilder_.build();
        }
        result.messageType_ = messageType_;
        result.textString_ = textString_;
        result.messageSource_ = messageSource_;
        result.voiceLength_ = voiceLength_;
        result.voiceData_ = voiceData_;
        result.token_ = token_;
        result.messageId_ = messageId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hoggen.sublimation.proto.MessageModel.YLMessageModel) {
          return mergeFrom((com.hoggen.sublimation.proto.MessageModel.YLMessageModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hoggen.sublimation.proto.MessageModel.YLMessageModel other) {
        if (other == com.hoggen.sublimation.proto.MessageModel.YLMessageModel.getDefaultInstance()) return this;
        if (other.hasFromUser()) {
          mergeFromUser(other.getFromUser());
        }
        if (other.hasToUser()) {
          mergeToUser(other.getToUser());
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (!other.getTextString().isEmpty()) {
          textString_ = other.textString_;
          onChanged();
        }
        if (!other.getMessageSource().isEmpty()) {
          messageSource_ = other.messageSource_;
          onChanged();
        }
        if (other.getVoiceLength() != 0) {
          setVoiceLength(other.getVoiceLength());
        }
        if (other.getVoiceData() != com.google.protobuf.ByteString.EMPTY) {
          setVoiceData(other.getVoiceData());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hoggen.sublimation.proto.MessageModel.YLMessageModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hoggen.sublimation.proto.MessageModel.YLMessageModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.hoggen.sublimation.proto.MessageModel.YLUserModel fromUser_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hoggen.sublimation.proto.MessageModel.YLUserModel, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder, com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder> fromUserBuilder_;
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public boolean hasFromUser() {
        return fromUserBuilder_ != null || fromUser_ != null;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public com.hoggen.sublimation.proto.MessageModel.YLUserModel getFromUser() {
        if (fromUserBuilder_ == null) {
          return fromUser_ == null ? com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance() : fromUser_;
        } else {
          return fromUserBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public Builder setFromUser(com.hoggen.sublimation.proto.MessageModel.YLUserModel value) {
        if (fromUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromUser_ = value;
          onChanged();
        } else {
          fromUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public Builder setFromUser(
          com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder builderForValue) {
        if (fromUserBuilder_ == null) {
          fromUser_ = builderForValue.build();
          onChanged();
        } else {
          fromUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public Builder mergeFromUser(com.hoggen.sublimation.proto.MessageModel.YLUserModel value) {
        if (fromUserBuilder_ == null) {
          if (fromUser_ != null) {
            fromUser_ =
              com.hoggen.sublimation.proto.MessageModel.YLUserModel.newBuilder(fromUser_).mergeFrom(value).buildPartial();
          } else {
            fromUser_ = value;
          }
          onChanged();
        } else {
          fromUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public Builder clearFromUser() {
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
          onChanged();
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder getFromUserBuilder() {
        
        onChanged();
        return getFromUserFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      public com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder getFromUserOrBuilder() {
        if (fromUserBuilder_ != null) {
          return fromUserBuilder_.getMessageOrBuilder();
        } else {
          return fromUser_ == null ?
              com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance() : fromUser_;
        }
      }
      /**
       * <pre>
       *发送人
       * </pre>
       *
       * <code>.YLUserModel fromUser = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hoggen.sublimation.proto.MessageModel.YLUserModel, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder, com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder> 
          getFromUserFieldBuilder() {
        if (fromUserBuilder_ == null) {
          fromUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hoggen.sublimation.proto.MessageModel.YLUserModel, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder, com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder>(
                  getFromUser(),
                  getParentForChildren(),
                  isClean());
          fromUser_ = null;
        }
        return fromUserBuilder_;
      }

      private com.hoggen.sublimation.proto.MessageModel.YLUserModel toUser_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hoggen.sublimation.proto.MessageModel.YLUserModel, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder, com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder> toUserBuilder_;
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public boolean hasToUser() {
        return toUserBuilder_ != null || toUser_ != null;
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public com.hoggen.sublimation.proto.MessageModel.YLUserModel getToUser() {
        if (toUserBuilder_ == null) {
          return toUser_ == null ? com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance() : toUser_;
        } else {
          return toUserBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public Builder setToUser(com.hoggen.sublimation.proto.MessageModel.YLUserModel value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          toUser_ = value;
          onChanged();
        } else {
          toUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public Builder setToUser(
          com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          toUser_ = builderForValue.build();
          onChanged();
        } else {
          toUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public Builder mergeToUser(com.hoggen.sublimation.proto.MessageModel.YLUserModel value) {
        if (toUserBuilder_ == null) {
          if (toUser_ != null) {
            toUser_ =
              com.hoggen.sublimation.proto.MessageModel.YLUserModel.newBuilder(toUser_).mergeFrom(value).buildPartial();
          } else {
            toUser_ = value;
          }
          onChanged();
        } else {
          toUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public Builder clearToUser() {
        if (toUserBuilder_ == null) {
          toUser_ = null;
          onChanged();
        } else {
          toUser_ = null;
          toUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder getToUserBuilder() {
        
        onChanged();
        return getToUserFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      public com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder getToUserOrBuilder() {
        if (toUserBuilder_ != null) {
          return toUserBuilder_.getMessageOrBuilder();
        } else {
          return toUser_ == null ?
              com.hoggen.sublimation.proto.MessageModel.YLUserModel.getDefaultInstance() : toUser_;
        }
      }
      /**
       * <pre>
       *送达人
       * </pre>
       *
       * <code>.YLUserModel toUser = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.hoggen.sublimation.proto.MessageModel.YLUserModel, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder, com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder> 
          getToUserFieldBuilder() {
        if (toUserBuilder_ == null) {
          toUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.hoggen.sublimation.proto.MessageModel.YLUserModel, com.hoggen.sublimation.proto.MessageModel.YLUserModel.Builder, com.hoggen.sublimation.proto.MessageModel.YLUserModelOrBuilder>(
                  getToUser(),
                  getParentForChildren(),
                  isClean());
          toUser_ = null;
        }
        return toUserBuilder_;
      }

      private int messageType_ ;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 messageType = 3;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 messageType = 3;</code>
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>uint32 messageType = 3;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object textString_ = "";
      /**
       * <pre>
       *消息字符
       * </pre>
       *
       * <code>string textString = 4;</code>
       */
      public java.lang.String getTextString() {
        java.lang.Object ref = textString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          textString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息字符
       * </pre>
       *
       * <code>string textString = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTextStringBytes() {
        java.lang.Object ref = textString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息字符
       * </pre>
       *
       * <code>string textString = 4;</code>
       */
      public Builder setTextString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        textString_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息字符
       * </pre>
       *
       * <code>string textString = 4;</code>
       */
      public Builder clearTextString() {
        
        textString_ = getDefaultInstance().getTextString();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息字符
       * </pre>
       *
       * <code>string textString = 4;</code>
       */
      public Builder setTextStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        textString_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageSource_ = "";
      /**
       * <pre>
       *消息资源地址（如图片、视频、文件）
       * </pre>
       *
       * <code>string messageSource = 5;</code>
       */
      public java.lang.String getMessageSource() {
        java.lang.Object ref = messageSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageSource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息资源地址（如图片、视频、文件）
       * </pre>
       *
       * <code>string messageSource = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageSourceBytes() {
        java.lang.Object ref = messageSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息资源地址（如图片、视频、文件）
       * </pre>
       *
       * <code>string messageSource = 5;</code>
       */
      public Builder setMessageSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息资源地址（如图片、视频、文件）
       * </pre>
       *
       * <code>string messageSource = 5;</code>
       */
      public Builder clearMessageSource() {
        
        messageSource_ = getDefaultInstance().getMessageSource();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息资源地址（如图片、视频、文件）
       * </pre>
       *
       * <code>string messageSource = 5;</code>
       */
      public Builder setMessageSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageSource_ = value;
        onChanged();
        return this;
      }

      private int voiceLength_ ;
      /**
       * <pre>
       *录音时长
       * </pre>
       *
       * <code>uint32 voiceLength = 6;</code>
       */
      public int getVoiceLength() {
        return voiceLength_;
      }
      /**
       * <pre>
       *录音时长
       * </pre>
       *
       * <code>uint32 voiceLength = 6;</code>
       */
      public Builder setVoiceLength(int value) {
        
        voiceLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *录音时长
       * </pre>
       *
       * <code>uint32 voiceLength = 6;</code>
       */
      public Builder clearVoiceLength() {
        
        voiceLength_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString voiceData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *录音数据
       * </pre>
       *
       * <code>bytes voiceData = 7;</code>
       */
      public com.google.protobuf.ByteString getVoiceData() {
        return voiceData_;
      }
      /**
       * <pre>
       *录音数据
       * </pre>
       *
       * <code>bytes voiceData = 7;</code>
       */
      public Builder setVoiceData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        voiceData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *录音数据
       * </pre>
       *
       * <code>bytes voiceData = 7;</code>
       */
      public Builder clearVoiceData() {
        
        voiceData_ = getDefaultInstance().getVoiceData();
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 8;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 8;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 8;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string token = 8;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string messageId = 9;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string messageId = 9;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string messageId = 9;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string messageId = 9;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *token
       * </pre>
       *
       * <code>string messageId = 9;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:YLMessageModel)
    }

    // @@protoc_insertion_point(class_scope:YLMessageModel)
    private static final com.hoggen.sublimation.proto.MessageModel.YLMessageModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hoggen.sublimation.proto.MessageModel.YLMessageModel();
    }

    public static com.hoggen.sublimation.proto.MessageModel.YLMessageModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<YLMessageModel>
        PARSER = new com.google.protobuf.AbstractParser<YLMessageModel>() {
      public YLMessageModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new YLMessageModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<YLMessageModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<YLMessageModel> getParserForType() {
      return PARSER;
    }

    public com.hoggen.sublimation.proto.MessageModel.YLMessageModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_YLUserModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_YLUserModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_YLMessageModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_YLMessageModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024YLMessageModel.proto\";\n\013YLUserModel\022\016\n" +
      "\006userId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\016\n\006avatar\030\003 " +
      "\001(\t\"\330\001\n\016YLMessageModel\022\036\n\010fromUser\030\001 \001(\013" +
      "2\014.YLUserModel\022\034\n\006toUser\030\002 \001(\0132\014.YLUserM" +
      "odel\022\023\n\013messageType\030\003 \001(\r\022\022\n\ntextString\030" +
      "\004 \001(\t\022\025\n\rmessageSource\030\005 \001(\t\022\023\n\013voiceLen" +
      "gth\030\006 \001(\r\022\021\n\tvoiceData\030\007 \001(\014\022\r\n\005token\030\010 " +
      "\001(\t\022\021\n\tmessageId\030\t \001(\tB,\n\034com.hoggen.sub" +
      "limation.protoB\014MessageModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_YLUserModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_YLUserModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_YLUserModel_descriptor,
        new java.lang.String[] { "UserId", "Name", "Avatar", });
    internal_static_YLMessageModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_YLMessageModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_YLMessageModel_descriptor,
        new java.lang.String[] { "FromUser", "ToUser", "MessageType", "TextString", "MessageSource", "VoiceLength", "VoiceData", "Token", "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
