custom:
  flag: true
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  password: Vx4uJc2qZfJJnjkHs26fsw==
  url: jdbc:mysql://127.0.0.1:3306/7chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  username: WnplV/ietfQ=
logging:
  config: classpath:logback.xml
mapper_path: /mapper/**.xml
mybatis_config_file: mybatis-config.xml
qiniu-cloud:
  access-key: lwuiNQK07h_lCSXrg2E2lGHJIxxDnauMjNgxw5aL
  bucket: internethospital-dev
  domain: http://qnfilesdev.schlwyy.com
  secret-key: fBp48kiyTN0T3O3fhoJZiC3mDGUCiTRKpqDPYbQK
server:
  port: 8099
spring:
  devtools:
    restart:
      additional-paths: src/main/java
      exclude: static/**,public/**
  local-redis:
    database: 3
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 15000
  redis:
    database: 6
    host: 127.0.0.1
    password: Xinjin_611430
    pool:
      max-active: 1000
      max-idle: 20
      max-wait: 30000
      min-idle: 1
    port: 6379
    timeout: 15000
  dubbo:
    base-package: com.hoggen.sublimation.*.httpsevice
    application:
      name: customer-prod
    registry:
      address: zookeeper://127.0.0.1
      port: 2181
    protocol:
      name: dubbo
      port: 20798
    provider:
      retries: 0
      timeout: 60000
    consumer:
      retries: 2
      timeout: 60000
      check: false

type_alias_package: com.hoggen.sublimation.entity
upload-config:
  channel-qrcode-path: ihosdev/channelqrcode
  chat-path: ihosdev/chat
  coupon-qrcode-path: ihosdev/couponqrcode
  department-path: ihosdev/department
  doctor-portrait-path: ihosdev/doctorportrait
  doctor-qrcode-path: ihosdev/doctorqrcode
  first-diagnosis-path: ihosdev/first-diagnosis
  hospital-path: ihosdev/hospital
  image-shuffling-path: ihosdev/imageshuffling
  module-path: ihosdev/module
  multi-send-meesgae: ihosdev/multimessage
  nurse-portrait-path: ihosdev/nurseportrait
  nurse-qrcode-path: ihosdev/nurseqrcode
  organization-qrcode-path: ihosdev/organizationqrcode
  public-access-path: http://inthosfiles.rc.schlwyy.com
  return-visit-path: ihosdev/returnvisit
  user-portrait-path: ihosdev/userportrait


xxl-job:
  enable: true
  admin:
    address: http://127.0.0.1:5999/xxl-job-admin
  executor:
    appname: sublimation-xxl
    port: 59992
    logpath: ./xxlLogs